env:
  browser: true
  es2021: true
  node: true

globals:
  # vitest globals
  afterAll: true
  afterEach: true
  assert: true
  beforeAll: true
  beforeEach: true
  chai: true
  describe: true
  expect: true
  it: true
  suite: true
  test: true
  vi: true
  vitest: true

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 13
  sourceType: "module"
  ecmaFeatures:
    jsx: true

plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
  - import
  - prettier

settings:
  react:
    version: "detect"
  import/parsers:
    "@typescript-eslint/parser": [".ts", ".tsx"]
  import/resolver:
    typescript: {}

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended

ignorePatterns:
  - "**/generated/*.ts"
  - "**/generated/*.tsx"

rules:
  no-console: warn
  import/order:
    - warn
    - groups: ["builtin", "external", "internal"]
      pathGroups:
        - pattern: "@/**"
          group: internal
          position: before
        - pattern: "react"
          group: "external"
          position: "before"
      pathGroupsExcludedImportTypes: ["react"]
      newlines-between: "always"
      alphabetize:
        order: "asc"
        caseInsensitive: true
  prettier/prettier:
    - warn
    - useTabs: true
      tabWidth: 4
      printWidth: 100
  "@typescript-eslint/consistent-type-imports":
    - warn
    - { prefer: "type-imports" }
